__d("DateFormatConfig",["NativeModules"],function (e, t, n, r, i) {
    "use strict";
    var NativeModules/*o*/ = t("NativeModules").RKI18n,
        a = {
            numericDateOrder: ["m", "d", "y"],
            numericDateSeparator: "/",
            shortDayNames: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
            weekStart: 6,
            formats: {
                "D M d": "D M d",
                "D M d, Y": "D M d, Y",
                "D M j": "D M j",
                "D M j, y": "D M j, y",
                "F d, Y": "F d, Y",
                "F j, Y": "F j, Y",
                "F j, Y @ g:i A": "F j, Y @ g:i A",
                "F j, Y g:i a": "F j, Y g:i a",
                "F jS, g:ia": "F jS, g:ia",
                "F jS, Y": "F jS, Y",
                "F Y": "F Y",
                "g:ia F jS, Y": "g:ia F jS, Y",
                "g:iA l, F jS": "g:iA l, F jS",
                "g:ia M j": "g:ia M j",
                "g:ia M jS": "g:ia M jS",
                "g:ia, F jS": "g:ia, F jS",
                "g:iA, l M jS": "g:iA, l M jS",
                "H:I - M d, Y": "H:I - M d, Y",
                "l F d, Y": "l F d, Y",
                "l, F d, Y": "l, F d, Y",
                "l, F j": "l, F j",
                "l, F j, Y": "l, F j, Y",
                "l, F jS": "l, F jS",
                "l, F jS, g:ia": "l, F jS, g:ia",
                "l, M j": "l, M j",
                "l, M j, Y": "l, M j, Y",
                "l, M j, Y g:ia": "l, M j, Y g:ia",
                "M d, Y": "M d, Y",
                "M d, Y g:ia": "M d, Y g:ia",
                "M d, Y ga": "M d, Y ga",
                "M j, Y": "M j, Y",
                "M j, Y g:i A": "M j, Y g:i A",
                "M j, Y g:ia": "M j, Y g:ia",
                "M jS, g:ia": "M jS, g:ia",
                "M Y": "M Y",
                "M. d, Y": "M. d, Y",
                "D g:ia": "D g:ia",
                "F d": "F d",
                "F g": "F g",
                "F j": "F j",
                "F jS": "F jS",
                "l g:ia": "l g:ia",
                "M d": "M d",
                "M j": "M j",
                "M y": "M y",
                "M. d": "M. d",
                D: "D",
                "g A": "g A",
                "g:i": "g:i",
                "g:i A": "g:i A",
                "g:i a": "g:i a",
                "g:iA": "g:iA",
                "g:ia": "g:ia",
                "g:sa": "g:sa",
                "h:i a": "h:i a",
                "h:m:s m/d/Y": "h:m:s m/d/Y",
                j: "j",
                "m-d-y": "m-d-y",
                "m.d.y": "m.d.y",
                "m/d": "m/d",
                "m/d/Y": "m/d/Y",
                "m/d/y": "m/d/y",
                "m/d/Y g:ia": "m/d/Y g:ia",
                "m/d/y H:i:s": "m/d/y H:i:s",
                "m/d/Y h:m": "m/d/Y h:m",
                n: "n",
                "n/j": "n/j",
                "n/j, g:ia": "n/j, g:ia",
                "n/j/y": "n/j/y",
                Y: "Y",
                "Y-m-d": "Y-m-d",
                "Y/m/d": "Y/m/d",
                "y/m/d": "y/m/d"
            },
            ordinalSuffixes: {
                1: "st",
                2: "nd",
                3: "rd",
                4: "th",
                5: "th",
                6: "th",
                7: "th",
                8: "th",
                9: "th",
                10: "th",
                11: "th",
                12: "th",
                13: "th",
                14: "th",
                15: "th",
                16: "th",
                17: "th",
                18: "th",
                19: "th",
                20: "th",
                21: "st",
                22: "nd",
                23: "rd",
                24: "th",
                25: "th",
                26: "th",
                27: "th",
                28: "th",
                29: "th",
                30: "th",
                31: "st"
            }
        };
    i.exports = NativeModules/*o*/.dateFormatConfig || a
});